export enum UserRole {
  STUDENT='STUDENT',
  PLACEMENT_REPRESENTATIVE='PLACEMENT_REPRESENTATIVE',
  TUTOR='TUTOR',
  COURSE_COORDINATOR='COURSE_COORDINATOR',
  PLACEMENT_COORDINATOR='PLACEMENT_COORDINATOR',
}
